chore: moved the top tabs from editor to extensions (Breaking change)
zalify/easy-email pull request #232
Opened 2023-02-09 20:45 UTC by wilau2

- Ran an import cleanup in the project since I've seen many of them. 
- Deleted a duplicated `classnames` file
- Move `Tags` an `Button` components from `@extension` to `@editor`
- Editor now exposes the 3 components (editorPreview, desktopPreview, mobilePreview)

This would be a breaking change:
From demo import `StandardEmailEditor` from `@extension` instead of `emailEditor` from `@editor`

2023-02-09 20:52 UTC, wilau2 commented on demo/src/pages/Editor/index.tsx
> -function replaceStandardBlockToAdvancedBlock(blockData: IBlockData) {
this was not used but I could remove the change if you want

2023-02-09 20:52 UTC, wilau2 commented on demo/src/pages/Editor/index.tsx
> -                <EmailEditor />
This is the breaking change here

2023-02-09 20:52 UTC, wilau2 commented on packages/easy-email-editor/src/components/EditEmailPreview/index.tsx
> +import '@/assets/font/iconfont.css';
I needed to move the font import here, I could not make it work from `@extension`

2023-02-09 20:52 UTC, wilau2 commented on packages/easy-email-editor/src/index.tsx
The breaking change is well seen here.

2023-02-09 20:52 UTC, wilau2 commented on packages/easy-email-extensions/src/utils/getPreviewClassName.ts
> -import { classnames } from '@extensions/AttributePanel/utils/classnames';
removed the dup classname function to use utils instead

2023-02-09 20:52 UTC, wilau2 commented on packages/easy-email-editor/src/utils/index.ts
> +export { EventManager, EventType } from './EventManager';
added this export here

2023-02-10 02:29 UTC, m-Ryan commented
Great job, we'll be done with the review this week.

2023-02-13 10:46 UTC, m-Ryan requested changes
The PR looks fine, but it looks like there will be a lot of conflicts with another PR.https://github.com/zalify/easy-email/pull/230
Most of the changes are formatting, maybe it can be solved by configuring eslint.

2023-02-20 19:23 UTC, wilau2 commented
closing this one for now since i'm running out of time and it was a breaking change refactor. Might reopen it later if I need it.

2023-02-20 19:23 UTC, closed without merging