feat: add jsonReadOnly prop
zalify/easy-email pull request #329
Opened 2023-06-19 13:37 UTC by fabien-roy

`mjmlReadOnly` prop was added and it's really useful. In our case, having `jsonReadOnly` would also be a good addition, since we want to control that.

- Add `jsonReadOnly` prop, similar to `mjmlReadOnly`
- Add readonly styles for text areas (remove focus/hover states, use disabled color text

2023-06-19 15:35 UTC, m-Ryan commented
@fabien-roy  Thank you for your PR, please check the comments of the review.

2023-06-19 15:35 UTC, m-Ryan approved these changes

2023-06-19 15:36 UTC, m-Ryan requested changes
Please check

2023-06-19 15:42 UTC, fabien-roy commented on packages/easy-email-extensions/src/index.scss
> +  }
My mistake, thanks!

2023-06-19 15:43 UTC, fabien-roy commented on packages/easy-email-extensions/src/StandardLayout/StandardLayout.tsx
> +    jsonReadOnly = true,
Right, disabled by default sounds like a better idea. I'll do that!

2023-06-20 02:15 UTC, m-Ryan approved these changes
LGBM

2023-06-20 02:15 UTC, merged

2023-06-20 02:18 UTC, m-Ryan commented
Released at  - easy-email-extensions@4.12.3